learning_log/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all topics
    url(r'^topics/$', views.topics, name='topics'),

    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # Page for adding a new topic.
    url(r'^newtopic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$',
        views.edit_entry, name='edit_entry'),

    # Page for displaying search results.
    url(r'^search/$', views.search, name='search'),

    # Show all booklists.
    url(r'^booklists/', views.booklists, name='booklists'),

    # Detail page for a single booklist
    url(r'^booklists/(?P<booklist_id>\d+)/$', views.books, name='books'),

    # Page for adding a new booklist.
    url(r'^newbooklist/$', views.new_booklist, name='new_booklist'),

    # Show all books.
    #url(r'^books/(?P<book_id>\d+)/$', views.books, name='books'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Login page
    url(r'^login/$', login,
        {'template_name': 'users/login.html'}, name='login'),

    # Registration page
    url(r'^register/$', views.register, name='register'),

    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=260)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."


class Booklist(models.Model):
    """A list of Books."""
    booklist_title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return self.booklist_title


class Book(models.Model):
    """books that belong to a list."""
    booklist = models.ForeignKey(Booklist)
    book_title = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.book_title

learning_logs/forms.py
from django import forms

from .models import Topic, Entry, Booklist


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class BooklistForm(forms.ModelForm):

    class Meta:
        model = Booklist
        fields = ['booklist_title']
        labels = {'booklist_title': ''}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry, Booklist, Book
from .forms import TopicForm, EntryForm, BooklistForm

# Create your views here.


def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    # topic = get_object_or_404(Topic, id=topic_id)
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        if check_topic_owner(request, topic_id):
            form = EntryForm()
        else:
            raise Http404
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        new_entry = form.save(commit=False)
        new_entry.topic = topic
        if form.is_valid():
            if check_topic_owner(request, topic_id):
                new_entry.save()
                return HttpResponseRedirect(reverse('learning_logs:topic',
                                                    args=[topic_id]))
            else:
                raise Http404

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    #topic = get_object_or_404(Topic, id=entry.topic.id)
    topic = entry.topic
    topic_id = entry.topic.id

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial rquest; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            if check_topic_owner(request, topic_id):
                form.save()
                return HttpResponseRedirect(reverse('learning_logs:topic',
                                                    args=[topic.id]))
            else:
                raise Http404

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(request, topic_id):
    """get user for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner == request.user:
        return True
    else:
        return False


def search(request):
    """Show search results."""
    if request.method != 'GET':
        raise Http404
    else:
        q = request.GET.get('searchquery', '')
        # api_url = 'http://openlibrary.org/search.json?title=' + q
        context = {'query': q}
        return render(request, 'learning_logs/search.html', context)


@login_required
def booklists(request):
    """Show all booklists"""
    booklists = Booklist.objects.filter(
        owner=request.user).order_by('date_added')
    context = {'booklists': booklists}
    return render(request, 'learning_logs/booklists.html', context)


@login_required
def books(request, booklist_id):
    """Show books for the given Booklist."""
    return render(request, 'learning_logs/index.html')


@login_required
def new_booklist(request):
    """Add a new booklist."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BooklistForm()
    else:
        # POST data submitted; process data.
        form = BooklistForm(request.POST)
        if form.is_valid():
            new_booklist = form.save(commit=False)
            new_booklist.owner = request.user
            new_booklist.save()
            return HttpResponseRedirect(reverse('learning_logs:booklists'))

    context = {'form': form}
    return render(request, 'learning_logs/new_booklist.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %} {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/sticky-footer.css' %}" type="text/css"/>
</head>

<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    <li><a href="{% url 'learning_logs:booklists' %}">Books</a></li>
                </ul>
                <!-- Search form -->
                <form action="{% url 'learning_logs:search' %}"class="navbar-form navbar-left" role="search" method="GET">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Book Search" name="searchquery">
                    </div>
                    <button type="submit" class="btn btn-default btn-large"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>  submit</button>
                </form>
                <!-- Search form end -->
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">register</a></li>
                    <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/ .nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
    <!-- /container -->
     </body>
    <footer class="footer">
      <div class="footer-container">
        <p class="text-muted">This website is licensed under the Creative Commons License and is free to distribute, copy and change.</p>
      </div>
    </footer>
   
</html>

learning_logs/templates/learning_logs/booklists.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Booklists</h1>
{% endblock header %}

{% block content %}
  
  <ul>
    {% for books in booklists %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:books' books.id %}">{{ books }}</a>
        </h3>
      </li>
        {% empty %}
          <li>No Booklists have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_booklist' %}">Add new booklist</a></h3>

{% endblock content %}

learning_logs/templates/learning_logs/books.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Books</h1>
{% endblock header %}

{% block content %}
  
  <ul>
    <p>Place Holder.</p>
  </ul>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

  <h4>Edit entry:</h4>
{% endblock header %}    

{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
    
    {% csrf_token %}
    {{ form.as_p }}

    {% buttons %}
    <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h2>Track your learning and maintain a booklist.</h2>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log,
    and list the topics you're learning about. You can also maintain a "BookList".
  </h2>
  <h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_booklist.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}

<h2>Add a new booklist:</h2> {% endblock header %} {% block content %}

<form action="{% url 'learning_logs:new_booklist' %}" method='POST' class="form">
    {% csrf_token %} 
    {% bootstrap_form form %} 
    {% buttons %}
    <button name="submit" class="btn btn-primary">add booklist</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}

<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>

{% endblock header %}    

{% block content %}
    <h4>Add a new entry:</h4>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST" class="form">
        
        {% csrf_token %}
        {{ form.as_p }}

    {% buttons %}
        <button name="submit" class="btn btn-primary">add entry</button>
    {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='POST' class="form">
    
    {% csrf_token %}
    {%  bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
    
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/search.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}

<h2>Search Results</h2>

{% endblock header %}

{% block content %}
    <p>Placeholder for results. You searched for {{ query }}.</p>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

{% for entry in entries %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
          </small>
        </h3>
  </div>
    <div class="panel-body">
      {{ entry.text|linebreaks }}
    </div>
  </div> <!-- panel -->
  
  {% empty %}
    There are no entries for this topic yet.
  
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
  
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
        {% empty %}
          <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</a></h3>

{% endblock content %}